modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/samolego/CubeRenderLib/issues"
license = "LGPL"

[[mods]]
modId = "cuberenderlib"
version = "${version}"
displayName = "Cube Render Library"
authors = "samo_lego"
description = '''
A server-side library used for rendering cube selections in Minecraft.
'''
#logoFile = ""

[[dependencies.cuberenderlib]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.cuberenderlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "SERVER"
